name: Change request
title: '[Change]'
description: Request any change you want that does not introduce a feature
labels: change
assignees: TabberApps2024

body:
  - type: textarea
    attributes:
      label: Feature Description
      description: "A clear and concise description of what the change is."
    validations:
      multiline: true
      required: true

  - type: dropdown
    attributes:
      label: Windows Version
      description: "Operating System"
      options:
        - Windows 8
        - Windows 10
        - Windows 11
        - All Above
    validations:
      required: true

  - type: textarea
    attributes:
      label: Other Information
      description: "Add any other context about the change here."
    validations:
      multiline: true
      required: false
