name: Feature request
title: '[Feature]'
description: Request any features you want added
labels: feature
assignees: TabberApps2024

body:
  - type: textarea
    attributes:
      label: Feature Description
      description: "A clear and concise description of what the feature is."
    validations:
      multiline: true
      required: true

  - type: dropdown
    attributes:
      label: Windows Version
      description: "Operating System"
      options:
        - Windows 8
        - Windows 10
        - Windows 11
    validations:
      required: true

  - type: textarea
    attributes:
      label: Other Information
      description: "Add any other context about the feature here."
    validations:
      multiline: true
      required: false
